//Author: Louis Scheffer V
//CSC309 project demonstration page
"use strict";

const fv = new FormationVisualizer()
fv.drawPitch()
fv.addPlayerTeam1("GK", "Hugo Lloris" , 1)
fv.addPlayerTeam1("LB", "Danny Rose" , 3)
fv.addPlayerTeam1("LCB", "Toby Alderweireld" , 4)
fv.addPlayerTeam1("CCB", "Kevin Wimmer" , 21)
fv.addPlayerTeam1("RCB", "Jan Vertonghen" , 5)
fv.addPlayerTeam1("RB", "Kyle Walker" , 2)
fv.addPlayerTeam1("LWB", "Dele Alli" , 20)
fv.addPlayerTeam1("RWB", "Kieran Trippier" , 22)
fv.addPlayerTeam1("CDM", "Victor Wanyama" , 12)
fv.addPlayerTeam1("CAM", "Christian Eriksen" , 23)
fv.addPlayerTeam1("LCM", "Moussa Sissoko" , 19)
fv.addPlayerTeam1("RCM", "Mousa Dembele" , 18)
fv.addPlayerTeam1("LM", "Hueng Min Son" , 7)
fv.addPlayerTeam1("RM", "Lucas Moura" , 17)
fv.addPlayerTeam1("LW", "Bryan Gil" , 11)
fv.addPlayerTeam1("RW", "Steven Bergwijn" , 23)
fv.addPlayerTeam1("LST", "Carlos Vinicius" , 45)
fv.addPlayerTeam1("RST", "Emmanuel Adebayor" , 22)
fv.addPlayerTeam1("CF", "Harry Kane" , 10)

fv.addPlayerTeam2("GK", "Hugo Lloris" , 1)
fv.addPlayerTeam2("LB", "Danny Rose" , 3)
fv.addPlayerTeam2("LCB", "Toby Alderweireld" , 4)
fv.addPlayerTeam2("CCB", "Kevin Wimmer" , 21)
fv.addPlayerTeam2("RCB", "Jan Vertonghen" , 5)
fv.addPlayerTeam2("RB", "Kyle Walker" , 2)
fv.addPlayerTeam2("LWB", "Dele Alli" , 20)
fv.addPlayerTeam2("RWB", "Kieran Trippier" , 22)
fv.addPlayerTeam2("CDM", "Victor Wanyama" , 12)
fv.addPlayerTeam2("CAM", "Christian Eriksen" , 23)
fv.addPlayerTeam2("LCM", "Moussa Sissoko" , 19)
fv.addPlayerTeam2("RCM", "Mousa Dembele" , 18)
fv.addPlayerTeam2("LM", "Hueng Min Son" , 7)
fv.addPlayerTeam2("RM", "Lucas Moura" , 17)
fv.addPlayerTeam2("LW", "Bryan Gil" , 11)
fv.addPlayerTeam2("RW", "Steven Bergwijn" , 23)
fv.addPlayerTeam2("LST", "Carlos Vinicius" , 45)
fv.addPlayerTeam2("RST", "Emmanuel Adebayor" , 22)
fv.addPlayerTeam2("CF", "Harry Kane" , 10)